### ISSUE TITLE
Allow looping?

### ISSUE THREAD

**Issue by Neo42** [dai-shi/excalidraw-animate#10]
Is there any possibility to set if the SVG animation should loop?

I made a diagram animation with excalidraw-animate for one of my blog posts. Since it only plays once, the animation is already done when readers scroll the page down to where the diagram is. It would be nice if it's possible to allow it to loop itself.

Thanks.

**Comment by dai-shi** [comment]
So, do you embed an svg file in your blog post? If you don't mind, can you share?

**Comment by dai-shi** [comment]
implementation memo: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/begin `<syncbase-value>` might help...

**Comment by Neo42** [comment]
> So, do you embed an svg file in your blog post? If you don't mind, can you share?

Thanks for replying! Here is the [svg file](https://neo42.cc/images/fiber.svg) and the [corresponding blog section](https://neo42.cc/posts/build-a-mini-react-from-scratch-to-suspense/#heading-fibers).

> implementation memo: developer.mozilla.org/en-US/docs/Web/SVG/Attribute/begin <syncbase-value> might help...

Thanks for the hint. Will look it up. Closing this issue for now.

**Comment by dai-shi** [comment]
Cool. You use `<object>`. Yeah, that's only the way to make it work.
If you want to solve it quickly on your end, you want to add JS in the svg.
I can look into it later.
To fully support this feature in the tool, it would require quite some effort.

**Comment by dai-shi** [comment]
OK, it works. Add this JS code in the svg file.
```js
    setInterval(() => {
      document.getElementsByTagName('svg')[0].setCurrentTime(0);      
    }, 18 * 1000);                                                            
```

[fiber.zip](https://github.com/dai-shi/excalidraw-animate/files/6404794/fiber.zip)

You could also restart animation on click if you want.

**Comment by dai-shi** [comment]
That's good!
Good question. Well, let me close this, as I won't work on it meanwhile and it would require refactoring.
