### ISSUE TITLE
Text is drawn by character only when left-aligned

### ISSUE THREAD

**Issue by osirisguitar** [dai-shi/excalidraw-animate#17]
Reproduce:

1. Create text
2. Set alignment to center
3. Create animation

Centered text appears as a single object, instead of one character at a time.

**Comment by dai-shi** [comment]
This is a known limitation because of how SVG works. I was hoping to support it too, but seems impossible. As workaround, centered (and right-aligned) text is animated with `opacity`, which is somewhat useful.
So, please use left-aligned text for typewriter like animation.
