### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined in renderElementToSvg (element.font seems to be missing)

### ISSUE THREAD

**Issue by sompylasar** [dai-shi/excalidraw-animate#2]
Can't share the JSON that caused it, but I guess some edge case is not handled.

```
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at renderElementToSvg (main.js:980)
    at main.js:871
    at Array.forEach (<anonymous>)
    at renderSceneToSvg (main.js:869)
    at exportToSvg (main.js:577)
    at main (main.js:294)
```

https://github.com/dai-shi/excalidraw-animate/blob/3f32dbc155822266eb9cead4e4dceb311ebfd135/public/main.js#L980

**Comment by dai-shi** [comment]
Thanks for reporting. This is due to the recent change in the upstream. We should eventually integrate better with it (currently copy&paste... 😓 ).

**Comment by dai-shi** [comment]
> (currently copy&paste... 😓 ).

Now, I made it to use git submodule. It should be easier to follow the upstream.
