### ISSUE TITLE
config the animation spped

### ISSUE THREAD

**Issue by lili21** [dai-shi/excalidraw-animate#21]
this would be helpful. currently, the speed is a little bit fast.

**Comment by dai-shi** [comment]
Hi! excalidraw-animate exposes a (hacky/undocumented) way to configure the animation duration.
We made fairly friendly UI integrated in [excalidraw-claymate](http://github.com/dai-shi/excalidraw-claymate).
See this tweet: https://twitter.com/dai_shi/status/1407360080568221698
