### ISSUE TITLE
[new feature] keep animating the arrow with lines

### ISSUE THREAD

**Issue by mawnir** [dai-shi/excalidraw-animate#41]
For example, after finishing the animation: keep the dotted arrow/line animated
https://excalidraw.com/#json=ChYHiaWabxSyCl6oX83ak,nFmcx4UF1Cqycy3zZcbOgg
like in this video:
https://www.youtube.com/watch?v=rZpR9DyM_qs
if you can guide me on where to start, it would be great!
Thank you!!

**Comment by dai-shi** [comment]
It would be nice, but there are some challenges:
- customizing animation is tricky because our input is the json file only.
- repeating sequence isn't straightforward. can be solved with https://stackoverflow.com/questions/3629987/how-to-loop-svg-animation-sequence
- the implementation is not very customizable (yet).

That said, please feel free to fork the repo and give a try.

**Comment by mawnir** [comment]
Hello again, I tried many things, and I failed.. I even asked Chatgpt.
I tried to add animate.setAttribute("repeatCount", "indefinite"); but it's not what I'm looking for since it starts from the beginning.
My SO question: https://stackoverflow.com/questions/75117813/animate-loop-a-dashed-svg-line 
if you have any ideas, it would be great.

**Comment by dai-shi** [comment]
As you may notice, this library is just a tool to convert excal json file to svg file.
So, the first thing you try is to create an svg file by hand (without any JavaScript) to realize what you want to do. Then, the next step would be to create a tool to generate it.
The first thing shouldn't be too difficult if you learn SVG basics. https://developer.mozilla.org/en-US/docs/Web/SVG

**Comment by mawnir** [comment]
Thank you, I can do that: https://raw.githubusercontent.com/mawnir/excalidraw-animate/main/src/test.html
but, my goal is to make things faster, create the sketch in excali then use this tool to animate it.

**Comment by dai-shi** [comment]
Nice. How can you do to repeat animating an arrow after drawing something with animation?
![image](https://user-images.githubusercontent.com/490574/212588434-585557f9-50d1-40b7-b790-f8f568b90bbc.png)

Then, the next step is to modify a simple svg file generated with excalidraw-animate, by hand to add repeated animation.
Finally, do it with code.

**Comment by mawnir** [comment]
Thank you so much, this line did it:
`<animate attributeName="stroke-dashoffset" values="300;0" dur="5s" repeatCount="indefinite" fill="freeze" />`

**Comment by dai-shi** [comment]
Oh, is it that easy! I didn't know that. Nice you find it. Thanks!

**Comment by mawnir** [comment]
> that easy! I didn't know that. Nice you find it.
No problem!
in the Library i added :
`const kanimate = svg.ownerDocument.createElementNS(SVG_NS, "animate");
    kanimate.setAttribute("attributeName", "stroke-dashoffset");
    kanimate.setAttribute("values", "300;0");
    kanimate.setAttribute("dur", "5s");
    kanimate.setAttribute("repeatCount", "indefinite");
    kanimate.setAttribute("fill", "freeze");
    ele.appendChild(kanimate);
` 
https://github.com/mawnir/excalidraw-animate/blob/main/src/animate.ts => line 145
and it worked! no need to export the SVG.
