### ISSUE TITLE
Play it backwards

### ISSUE THREAD

**Issue by sevketufuk** [dai-shi/excalidraw-animate#48]
I'm searching a way to play the animation backwards just like a video, I tried multiple ways but no success! Is there anyway of doing it?
Thanks!

**Comment by dai-shi** [comment]
I wonder if SVG's setCurrentTime helps, but it doesn't seem as I hoped.

I think what's easy is to reverse the video. video editing.

**Comment by sevketufuk** [comment]
Video is not an option for me, i try to build something like a video with a progress bar etc. however user should be able play everything in reverse order. thanks for the answer though!
