### ISSUE TITLE
Export to WebM error

### ISSUE THREAD

**Issue by winkler1** [dai-shi/excalidraw-animate#5]
Amazing project! Got this trying to export to WebM

TypeError: Failed to execute 'showSaveFilePicker' on 'Window': Invalid type: video/webm;codecs=vp8
    at file-save.mjs:2

**Comment by dai-shi** [comment]
Confirmed the issue. "Export to SVG" doesn't work either.
Maybe, it's broken by the upstream updates lately. Will investigate.

**Comment by dai-shi** [comment]
I fixed the error, but then found the exported file is empty canvas. Something seems wrong, but no clue to fix it. Meanwhile, please use any capturing tool to record your screen.

**Comment by dai-shi** [comment]
I'm thinking of re-implementing the export to video feature with screen capture api + mediastream recording api.
https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API
https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

**Comment by dai-shi** [comment]
Fixed: https://twitter.com/dai_shi/status/1344935241668988930
