### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by warmachinesocial** [dai-shi/excalidraw-animate#54]
Firstly, man this is an awesome tool like seriously hats off to you and everyone who's working on this. I love svg but want gif support such that it plays in loop. To be honest I don't know about file formats and graphics but any links I could even pull PR up

**Comment by dai-shi** [comment]
It's out of the scope of excalidraw-animate, but it might be the scope of excalidraw-claymate as it exports as gif (claymation not animation 😄 ).
But, to be honest, creating git animation is tedious, so I recommend to record screen and convert movie to gif using a tool like ffmpeg.
