### ISSUE TITLE
How to retain the background color

### ISSUE THREAD

**Issue by SevenJess** [dai-shi/excalidraw-animate#6]
It seems that regardless of any background color set for the entire board, it stays white. Is there a way to change the background in the animation?

**Comment by dai-shi** [comment]
Right, it's because the background color is not the part of SVG. If you export an svg file in the official Excalidraw, the background color is not set.

That said, I also felt I need this feature. Maybe we can set the background color at html level.

**Comment by dai-shi** [comment]
Oh, my bad. There's an option to export the background.
