### ISSUE TITLE
Change order of animations?

### ISSUE THREAD

**Issue by slimsag** [dai-shi/excalidraw-animate#7]
Very cool tool, nice work!

I would find this much more powerful if it was possible to change the order of animations. Currently it is based on the order of created objects in excalidraw - but if manual re-ordering of objects was possible it would be easy to create "visual tutorials" using excalidraw and I would **love** this.

**Comment by dai-shi** [comment]
Thanks for the feedback.
What you can do now is to change the layer in the excalidraw app.
I know it's not very handy, but it may work in a small use case.

**Comment by dai-shi** [comment]
As I wrote in the other issue, this tool is not going to be an authoring tool.
For such purpose, we would like to extend [excalidraw-claymate](https://github.com/dai-shi/excalidraw-claymate).

Changing the order of animations **can** be done with changing the order (layer) in Excalidraw. So, let me close this.

I know it's very hard with complex objects.
My another experimental tool to _visualize_ layers is [excalidraw-layers](https://github.com/dai-shi/excalidraw-layers).
